# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_control/MecanumControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MecanumControl(genpy.Message):
  _md5sum = "cc8cc5d29cc98dd7c83c44e13887d465"
  _type = "can_control/MecanumControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 MODE_CALIB       = 0
uint8 MODE_IDLE        = 1
uint8 MODE_CLOSE_LOOP  = 2
uint8 MODE_CLEAR_ERROR = 3
uint8 MODE_HOMING      = 4
uint8 MODE_SET_TARGET  = 5

uint8 device_id
uint8 mode
float32 value
"""
  # Pseudo-constants
  MODE_CALIB = 0
  MODE_IDLE = 1
  MODE_CLOSE_LOOP = 2
  MODE_CLEAR_ERROR = 3
  MODE_HOMING = 4
  MODE_SET_TARGET = 5

  __slots__ = ['device_id','mode','value']
  _slot_types = ['uint8','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       device_id,mode,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MecanumControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.device_id is None:
        self.device_id = 0
      if self.mode is None:
        self.mode = 0
      if self.value is None:
        self.value = 0.
    else:
      self.device_id = 0
      self.mode = 0
      self.value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bf().pack(_x.device_id, _x.mode, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.device_id, _x.mode, _x.value,) = _get_struct_2Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bf().pack(_x.device_id, _x.mode, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.device_id, _x.mode, _x.value,) = _get_struct_2Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bf = None
def _get_struct_2Bf():
    global _struct_2Bf
    if _struct_2Bf is None:
        _struct_2Bf = struct.Struct("<2Bf")
    return _struct_2Bf
